ALTER TABLE [dbo].[UserContacts]
    ADD CONSTRAINT [PK_UserContacts] PRIMARY KEY CLUSTERED ([UserId] ASC, [ContactId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

