//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRS.InvoiceTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid Id { get; set; }
        public string Postalcode { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
